export const XP_REWARDS = {
  AM_INTENT: 10,
  PM_REVIEW: 10,
  QUICK_LOG: 2,
  WEIGHT_LOG: 5,
  URGE_RESISTED: 15,
  URGE_COOLDOWN: 5,
  HABIT_COMPLETE: 5,
  TASK_DONE: 3,
  IDENTITY_SET: 20,
  SHOCK_DISMISS: 1,
  SLEEP_ON_TIME: 8,
} as const;

export const SCORE_DELTAS = {
  DAILY_ENGAGEMENT: 2,
  URGE_RESISTED: 4,
  URGE_ACTED: -6,
  MISSED_DAY: -1,
  STREAK_BROKEN: -5,
} as const;
